"""Synthetic files shipped inside a workspace-export zip.

The Modal sandbox preamble in :mod:`services.sandbox` injects a `trainable`
module whose helpers write into the volume at well-known paths. When the
user downloads their session's workspace, the agent's scripts still
reference `from trainable import log, log_image, ...` — so the zip ships
a local shim that resolves those imports against the user's filesystem
instead of the volume.

The shim's *surface* (method names + arity) must match the sandbox
preamble. When you add a helper there, mirror it here, otherwise the
downloaded scripts will `AttributeError` on unfamiliar Python.
"""

from __future__ import annotations

from datetime import datetime, timezone


# Local shim — written verbatim into the zip as `trainable_local.py`.
# Importing this file (or having it on sys.path under the name `trainable`)
# gives the downloaded scripts the same `trainable.log(...)` API they
# used in the sandbox, but rerouted to `./trainable_out/`.
LOCAL_SHIM = '''\
"""Local trainable shim (auto-generated by the workspace exporter).

Drop this file anywhere on sys.path and `import trainable` will resolve
to this shim. Helpers write to ./trainable_out/ instead of the Modal
volume the cloud agent used. Override the output root with the
TRAINABLE_LOCAL_OUT environment variable.

This is best-effort parity with the cloud SDK — `log`/`log_image`/etc.
all work, but advanced features (live SSE broadcast, server-side chart
configuration) are no-ops. The point is to make downloaded scripts RUN
locally without `NameError`, not to mirror the studio experience.
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import sys
import time
import types


_OUT = pathlib.Path(os.environ.get("TRAINABLE_LOCAL_OUT", "./trainable_out")).resolve()
_OUT.mkdir(parents=True, exist_ok=True)
_FIG_BASE = _OUT / "figures"
_HTML_BASE = _OUT / "html"
_METRICS_FILE = _OUT / "metrics.jsonl"
_LOG_FILE = _OUT / "log_events.jsonl"
_TABLE_ROW_LIMIT = 1000


def _safe_key(key) -> str:
    return re.sub(r"[^A-Za-z0-9_./-]", "_", str(key)).strip("/") or "log"


def _append_jsonl(path: pathlib.Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(payload) + "\\n")


def _save_image(img, dest_path: pathlib.Path) -> None:
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(img, (str, bytes, os.PathLike)):
        src = os.fspath(img)
        if str(src) == str(dest_path):
            return
        with open(src, "rb") as r, open(dest_path, "wb") as w:
            w.write(r.read())
        return
    try:
        from PIL import Image as _PILImage  # type: ignore

        if isinstance(img, _PILImage.Image):
            img.convert("RGB").save(dest_path, format="PNG")
            return
    except Exception:
        pass
    try:
        import numpy as _np  # type: ignore

        if isinstance(img, _np.ndarray):
            from PIL import Image as _PILImage  # type: ignore

            arr = img
            if arr.dtype != _np.uint8:
                a = arr.astype(_np.float32)
                if a.max() <= 1.0 + 1e-6:
                    a = a * 255.0
                arr = a.clip(0, 255).astype(_np.uint8)
            if arr.ndim == 2:
                _PILImage.fromarray(arr, mode="L").save(dest_path, format="PNG")
            elif arr.ndim == 3 and arr.shape[2] == 4:
                _PILImage.fromarray(arr, mode="RGBA").save(dest_path, format="PNG")
            else:
                _PILImage.fromarray(arr).convert("RGB").save(dest_path, format="PNG")
            return
    except Exception:
        pass
    raise TypeError("log_image: unsupported image type %r" % (type(img),))


def log(step, metrics, run=None):
    payload = {
        "ts": time.time(),
        "step": int(step),
        "metrics": {k: float(v) for k, v in dict(metrics).items()},
    }
    if run:
        payload["run"] = str(run)
    _append_jsonl(_METRICS_FILE, payload)
    print(f"[trainable] step={payload['step']} {payload['metrics']}")


def configure_dashboard(charts):
    (_OUT / "dashboard.json").write_text(json.dumps({"charts": charts}, indent=2))


def log_image(step, key, image, caption=None, run=None):
    safe = _safe_key(key)
    dest = _FIG_BASE / safe / f"{int(step)}.png"
    _save_image(image, dest)
    payload = {
        "type": "image",
        "step": int(step),
        "key": safe,
        "path": str(dest.relative_to(_OUT)),
    }
    if caption:
        payload["caption"] = str(caption)
    if run:
        payload["run"] = str(run)
    _append_jsonl(_LOG_FILE, payload)


def log_images(step, key, images, captions=None, run=None):
    safe = _safe_key(key)
    items = []
    for i, img in enumerate(images):
        dest = _FIG_BASE / safe / f"{int(step)}_{i}.png"
        _save_image(img, dest)
        item = {"path": str(dest.relative_to(_OUT))}
        if captions and i < len(captions) and captions[i] is not None:
            item["caption"] = str(captions[i])
        items.append(item)
    payload = {"type": "image_grid", "step": int(step), "key": safe, "items": items}
    if run:
        payload["run"] = str(run)
    _append_jsonl(_LOG_FILE, payload)


def log_figure(step, key, fig, run=None):
    safe = _safe_key(key)
    dest = _FIG_BASE / safe / f"{int(step)}.png"
    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        fig.savefig(str(dest), format="png", bbox_inches="tight", dpi=120)
    except Exception as e:
        raise TypeError("log_figure: object is not a matplotlib Figure (%s)" % e)
    payload = {
        "type": "image",
        "step": int(step),
        "key": safe,
        "path": str(dest.relative_to(_OUT)),
    }
    if run:
        payload["run"] = str(run)
    _append_jsonl(_LOG_FILE, payload)


def log_table(step, key, columns, rows, run=None):
    cols = [str(c) for c in columns]
    rs = list(rows)[:_TABLE_ROW_LIMIT]
    norm = []
    for r in rs:
        row = list(r) if not isinstance(r, dict) else [r.get(c) for c in cols]
        norm.append(
            [
                None
                if v is None
                else (
                    float(v)
                    if isinstance(v, bool) is False and isinstance(v, (int, float))
                    else str(v)
                )
                for v in row
            ]
        )
    payload = {
        "type": "table",
        "step": int(step),
        "key": _safe_key(key),
        "columns": cols,
        "rows": norm,
        "truncated": len(list(rows)) > _TABLE_ROW_LIMIT,
    }
    if run:
        payload["run"] = str(run)
    _append_jsonl(_LOG_FILE, payload)


def log_confusion_matrix(step, key, y_true, y_pred, labels=None, run=None):
    try:
        from sklearn.metrics import confusion_matrix as _cm  # type: ignore

        labs = list(labels) if labels is not None else sorted(set(list(y_true) + list(y_pred)))
        m = _cm(y_true, y_pred, labels=labs).tolist()
    except Exception:
        labs = list(labels) if labels is not None else sorted(set(list(y_true) + list(y_pred)))
        idx = {lab: i for i, lab in enumerate(labs)}
        m = [[0] * len(labs) for _ in labs]
        for t, p in zip(y_true, y_pred):
            if t in idx and p in idx:
                m[idx[t]][idx[p]] += 1
    payload = {
        "type": "confusion_matrix",
        "step": int(step),
        "key": _safe_key(key),
        "labels": [str(lab) for lab in labs],
        "matrix": m,
    }
    if run:
        payload["run"] = str(run)
    _append_jsonl(_LOG_FILE, payload)


def show_html(html, *, title=None, key=None):
    name = _safe_key(key) if key else "artifact"
    dest = _HTML_BASE / f"{name}.html"
    dest.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(html, str):
        dest.write_text(html, encoding="utf-8")
    elif hasattr(html, "to_html"):
        dest.write_text(html.to_html(), encoding="utf-8")
    else:
        dest.write_text(str(html), encoding="utf-8")


_m = types.ModuleType("trainable")
_m.log = log
_m.configure_dashboard = configure_dashboard
_m.log_image = log_image
_m.log_images = log_images
_m.log_figure = log_figure
_m.log_table = log_table
_m.log_confusion_matrix = log_confusion_matrix
_m.show_html = show_html
sys.modules["trainable"] = _m
'''


# Subset of `backend/requirements.txt` actually useful for running the
# agent's downloaded scripts. Excludes server-only deps (FastAPI, modal,
# anthropic, opentelemetry, etc.) so a `pip install -r requirements.txt`
# from the zip stays small and quick.
LOCAL_REQUIREMENTS = """\
# Generated by the Trainable workspace exporter — minimal set to run
# agent-produced scripts locally. Mirrors what the cloud sandbox installs
# (see backend/services/sandbox.py:get_image).

pandas>=2.0.0
numpy>=1.24.0
scikit-learn>=1.3.0
matplotlib>=3.7.0
seaborn>=0.12.0
plotly>=5.18.0
xgboost>=2.0.0
lightgbm>=4.0.0
pyarrow>=14.0.0
duckdb>=1.0.0
openpyxl>=3.1.0
imbalanced-learn>=0.11.0
optuna>=3.4.0
category_encoders>=2.6.0
pandera>=0.18.0
shap>=0.43.0
statsmodels>=0.14.0
pypdf>=5.0.0
pillow>=10.0.0
jupyter>=1.0.0
nbformat>=5.10.0
"""


def render_readme(
    *, scope: str, identifier: str, file_count: int, total_bytes: int
) -> str:
    """Generate the README packaged at the zip root.

    `scope` is either "session" or "project" — affects the top-level
    description but the run instructions are identical.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    short = identifier[:8] if len(identifier) > 8 else identifier
    title = f"Trainable {scope} export — {short}"
    size_mb = total_bytes / (1024 * 1024)

    if scope == "project":
        layout_note = (
            "Each session is nested under `sessions/<slug>/`. Two sessions\n"
            "with identical labels are disambiguated by short-id suffix.\n"
        )
    else:
        layout_note = (
            "Files preserve the layout the agent wrote in the cloud, so\n"
            "imports between `src/` modules keep working unchanged.\n"
        )

    return f"""# {title}

Generated on {ts} from {scope} `{identifier}` ({file_count} files, {size_mb:.1f} MB).

## Run it locally

```bash
python -m venv .venv
source .venv/bin/activate          # Windows: .venv\\Scripts\\activate
pip install -r requirements.txt
python -c "import trainable_local"  # registers the local `trainable` shim
```

Once `trainable_local` is imported, any of the agent's scripts that do
`from trainable import log, log_image, ...` will work against your
filesystem. The simplest way to make the shim available to every script
is to drop a line at the top of your entrypoint:

```python
import trainable_local  # registers ./trainable_out/-backed `trainable` module
```

…or set `PYTHONSTARTUP=trainable_local.py` for a session-wide shim.

## What's inside

- `src/`             — agent-written Python modules (the session was a
                        proper Python package: `from features import ...`
                        works the same here).
- `notebooks/`       — Jupyter notebooks as-is.
- `figures/`         — image artifacts the agent logged.
- `scripts/`         — the audit trail of every sandbox call.
- `trainable_local.py` — local shim for the `trainable` SDK.
- `requirements.txt` — pinned subset of the cloud sandbox image.

{layout_note}

## What's NOT inside

- **Raw datasets.** The agent's scripts reference inputs by their original
  upload path (e.g. `/sessions/.../data/raw.csv`). Drop your local copy
  in place and adjust the path, or set the `DATA_DIR` env var if a script
  reads it.
- **The GPU/Modal environment.** Library versions are best-effort, not
  byte-identical. Scripts that pin specific GPU kernels or Modal-only
  paths may need light edits.
- **Round-trip telemetry.** `trainable.log(...)` writes to
  `./trainable_out/metrics.jsonl` here — nothing is sent back to the
  studio.
"""
