"""Trainable CLI — setup wizard and launcher."""

from __future__ import annotations

import getpass
import os
import shutil
import subprocess
import sys
import textwrap
import urllib.request
from pathlib import Path

REPO = "lucastononro/trainable"
BRANCH = "main"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"

COMPOSE_FILE = "docker-compose.prod.yml"
ENV_FILE = ".env"
PROJECT_NAME = "trainable"

# Config lives in ~/.trainable so `trainable up` works from any directory.
# Override via TRAINABLE_HOME env var for advanced users.
CONFIG_DIR = Path(os.environ.get("TRAINABLE_HOME", Path.home() / ".trainable"))

BOLD = "\033[1m"
DIM = "\033[2m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
CYAN = "\033[36m"
RED = "\033[31m"
RESET = "\033[0m"


def banner():
    print(
        textwrap.dedent(f"""\

        {BOLD}╔══════════════════════════════════════╗
        ║          trainable                   ║
        ║   AI-powered ML experimentation      ║
        ╚══════════════════════════════════════╝{RESET}
    """)
    )


def step(n: int, total: int, msg: str):
    print(f"\n{CYAN}{BOLD}[{n}/{total}]{RESET} {BOLD}{msg}{RESET}")


def success(msg: str):
    print(f"  {GREEN}✓{RESET} {msg}")


def warn(msg: str):
    print(f"  {YELLOW}!{RESET} {msg}")


def fail(msg: str):
    print(f"  {RED}✗{RESET} {msg}")


def prompt_secret(label: str, help_url: str | None = None) -> str:
    hint = f" {DIM}({help_url}){RESET}" if help_url else ""
    while True:
        value = getpass.getpass(f"  {label}{hint}: ").strip()
        if value:
            return value
        warn("Cannot be empty, try again.")


def prompt_choice(label: str, options: list[str]) -> int:
    print(f"  {label}")
    for i, opt in enumerate(options, 1):
        print(f"    {BOLD}{i}{RESET}) {opt}")
    while True:
        raw = input(f"  {DIM}Enter choice [1-{len(options)}]{RESET}: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return int(raw)
        warn(f"Please enter a number between 1 and {len(options)}")


def download_file(filename: str, dest: Path):
    url = f"{RAW_BASE}/{filename}"
    urllib.request.urlretrieve(url, dest / filename)
    success(f"Downloaded {filename}")


def check_docker():
    if not shutil.which("docker"):
        fail("Docker not found. Install it from https://docs.docker.com/get-docker/")
        sys.exit(1)
    result = subprocess.run(
        ["docker", "compose", "version"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail("Docker Compose not found. Install Docker Desktop or the compose plugin.")
        sys.exit(1)
    success("Docker and Docker Compose found")


# Names the wizard knows about explicitly; everything else is treated as a
# LiteLLM backend key in the free-form section.
_KNOWN_PROVIDER_KEYS = {
    "ANTHROPIC_API_KEY",
    "CLAUDE_CODE_OAUTH_TOKEN",
    "OPENAI_API_KEY",
    "GEMINI_API_KEY",
    "GOOGLE_API_KEY",
    "MODAL_TOKEN_ID",
    "MODAL_TOKEN_SECRET",
}


def read_env(dest: Path) -> dict[str, str]:
    """Parse an existing .env into a dict. Best-effort, comment-aware.

    Used so `trainable init` on top of an existing config can preserve the
    user's existing keys instead of forcing them to re-enter everything.
    """
    env_path = dest / ENV_FILE
    if not env_path.exists():
        return {}
    out: dict[str, str] = {}
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def write_env(dest: Path, config: dict[str, str]):
    lines = ["# Generated by: trainable init", ""]

    if config.get("ANTHROPIC_API_KEY"):
        lines += [
            "# Claude authentication (API key)",
            f"ANTHROPIC_API_KEY={config['ANTHROPIC_API_KEY']}",
        ]
    elif config.get("CLAUDE_CODE_OAUTH_TOKEN"):
        lines += [
            "# Claude authentication (subscription token — uses your Pro/Max quota)",
            f"CLAUDE_CODE_OAUTH_TOKEN={config['CLAUDE_CODE_OAUTH_TOKEN']}",
        ]

    if config.get("OPENAI_API_KEY"):
        lines += ["", "# OpenAI", f"OPENAI_API_KEY={config['OPENAI_API_KEY']}"]
    if config.get("GEMINI_API_KEY"):
        lines += ["", "# Gemini", f"GEMINI_API_KEY={config['GEMINI_API_KEY']}"]
    if config.get("GOOGLE_API_KEY") and not config.get("GEMINI_API_KEY"):
        # Either name works; only emit GOOGLE_API_KEY when GEMINI_API_KEY is unset.
        lines += [
            "",
            "# Gemini (alt env var)",
            f"GOOGLE_API_KEY={config['GOOGLE_API_KEY']}",
        ]

    # Generic LiteLLM-routed backend keys (free-form add-loop in the wizard).
    extra_keys = sorted(k for k in config.keys() if k not in _KNOWN_PROVIDER_KEYS)
    if extra_keys:
        lines += ["", "# LiteLLM backends"]
        for k in extra_keys:
            lines.append(f"{k}={config[k]}")

    lines += [
        "",
        "# Modal (sandboxed code execution)",
        f"MODAL_TOKEN_ID={config.get('MODAL_TOKEN_ID', '')}",
        f"MODAL_TOKEN_SECRET={config.get('MODAL_TOKEN_SECRET', '')}",
    ]

    env_path = dest / ENV_FILE
    env_path.write_text("\n".join(lines) + "\n")
    success(f"Wrote {ENV_FILE}")


def configured_providers(config: dict[str, str]) -> list[str]:
    """Return human-readable list of providers that look configured."""
    providers: list[str] = []
    if config.get("CLAUDE_CODE_OAUTH_TOKEN"):
        providers.append("Claude (subscription OAuth)")
    elif config.get("ANTHROPIC_API_KEY"):
        providers.append("Claude (API key)")
    if config.get("OPENAI_API_KEY"):
        providers.append("OpenAI")
    if config.get("GEMINI_API_KEY") or config.get("GOOGLE_API_KEY"):
        providers.append("Gemini")
    litellm_keys = sorted(
        k
        for k in config.keys()
        if k not in _KNOWN_PROVIDER_KEYS and k.endswith("_API_KEY")
    )
    if litellm_keys:
        backends = [k.removesuffix("_API_KEY").lower() for k in litellm_keys]
        providers.append(f"LiteLLM ({', '.join(backends)})")
    return providers


def prompt_claude_auth() -> dict[str, str]:
    print()
    choice = prompt_choice(
        "How would you like to authenticate with Claude?",
        [
            "Anthropic API key",
            "Claude subscription (Pro/Max) token",
        ],
    )
    print()

    if choice == 1:
        key = prompt_secret(
            "Anthropic API key",
            "https://console.anthropic.com",
        )
        return {"ANTHROPIC_API_KEY": key}

    # Subscription token flow
    print("  To get your subscription token, run this in another terminal:\n")
    print(f"    {BOLD}claude setup-token{RESET}\n")
    print("  Then paste the token below.\n")
    token = prompt_secret("Claude subscription token")
    return {"CLAUDE_CODE_OAUTH_TOKEN": token}


def prompt_openai_auth() -> dict[str, str]:
    print()
    choice = prompt_choice(
        "How would you like to authenticate with OpenAI?",
        [
            "OpenAI API key (works in dev and prod)",
            "ChatGPT-Plus via Codex CLI OAuth (local dev only)",
        ],
    )
    print()
    if choice == 1:
        key = prompt_secret("OpenAI API key", "https://platform.openai.com/api-keys")
        return {"OPENAI_API_KEY": key}
    print("  Codex OAuth is file-based — there's no token to paste. To set it up:\n")
    print(f"    {BOLD}npm install -g @openai/codex{RESET}")
    print(f"    {BOLD}codex login{RESET}\n")
    print(f"  Credentials land at {BOLD}~/.codex/auth.json{RESET}, which the dev")
    print("  docker-compose.yml mounts read-only into the backend container.")
    print(f"  {DIM}Production needs OPENAI_API_KEY — OAuth tokens rotate.{RESET}\n")
    input(f"  {DIM}Press Enter once codex login is complete (or skip){RESET}: ")
    return {}


def prompt_gemini_auth() -> dict[str, str]:
    print()
    choice = prompt_choice(
        "How would you like to authenticate with Gemini?",
        [
            "Gemini API key (works in dev and prod)",
            "Gemini CLI OAuth (local dev only)",
        ],
    )
    print()
    if choice == 1:
        key = prompt_secret("Gemini API key", "https://aistudio.google.com/apikey")
        return {"GEMINI_API_KEY": key}
    print(
        "  Gemini CLI OAuth is file-based — there's no token to paste. To set it up:\n"
    )
    print(f"    {BOLD}npm install -g @google/gemini-cli{RESET}")
    print(f"    {BOLD}gemini auth login{RESET}\n")
    print(f"  Credentials land at {BOLD}~/.gemini/oauth_creds.json{RESET}, which the")
    print("  dev docker-compose.yml mounts read-only into the backend container.")
    print(f"  {DIM}Production needs GEMINI_API_KEY — OAuth tokens rotate.{RESET}\n")
    input(f"  {DIM}Press Enter once gemini auth login is complete (or skip){RESET}: ")
    return {}


def prompt_litellm_keys() -> dict[str, str]:
    """Free-form add-loop for LiteLLM backend API keys (Groq, Mistral, etc.)."""
    print()
    print("  LiteLLM routes calls to many backends — each needs its own key env var.")
    print(
        f"  {DIM}Examples: GROQ_API_KEY, MISTRAL_API_KEY, TOGETHER_API_KEY, DEEPSEEK_API_KEY{RESET}\n"
    )
    out: dict[str, str] = {}
    while True:
        name = input(f"  Backend env var name {DIM}(blank to finish){RESET}: ").strip()
        if not name:
            break
        if not name.replace("_", "").isalnum():
            warn("Invalid env var name — letters / digits / underscores only.")
            continue
        out[name.upper()] = prompt_secret(f"{name.upper()} value")
    return out


def prompt_extra_providers(*, include_claude: bool = False) -> dict[str, str]:
    """Multi-select provider picker.

    From a fresh install, `prompt_claude_auth()` runs separately (Claude is
    mandatory) and this picker only offers OpenAI / Gemini / LiteLLM behind
    a y/N gate. From the "add to existing config" flow, Claude is included
    so the user can replace it without redoing the whole wizard, and the
    y/N gate is skipped (the user already said yes).
    """
    if not include_claude:
        print()
        answer = (
            input(
                f"  Configure additional LLM providers (OpenAI / Gemini / LiteLLM)?"
                f" {DIM}[y/N]{RESET}: "
            )
            .strip()
            .lower()
        )
        if answer not in ("y", "yes"):
            return {}

    print("\n  Select providers to configure (space-separated numbers, blank to skip):")
    options: list[tuple[str, str]] = []
    if include_claude:
        options.append(("claude", "Claude (Anthropic API key or subscription OAuth)"))
    options += [
        ("openai", "OpenAI (API key or Codex CLI OAuth)"),
        ("gemini", "Gemini (API key or Gemini CLI OAuth)"),
        ("litellm", "LiteLLM (catch-all: Groq, Mistral, DeepSeek, etc.)"),
    ]
    for i, (_, label) in enumerate(options, 1):
        print(f"    {BOLD}{i}{RESET}) {label}")
    raw = input(f"  {DIM}Choices [1-{len(options)}]{RESET}: ").strip()
    selected: list[str] = []
    for tok in raw.replace(",", " ").split():
        if tok.isdigit() and 1 <= int(tok) <= len(options):
            selected.append(options[int(tok) - 1][0])

    handlers = {
        "claude": prompt_claude_auth,
        "openai": prompt_openai_auth,
        "gemini": prompt_gemini_auth,
        "litellm": prompt_litellm_keys,
    }
    out: dict[str, str] = {}
    for key in selected:
        out.update(handlers[key]())
    return out


def _existing_config_choice(existing: dict[str, str]) -> str:
    """Ask what to do when ~/.trainable/.env already has values.

    Returns one of: "add" | "replace" | "cancel".
    """
    print()
    providers = configured_providers(existing)
    if providers:
        print(f"  {BOLD}Current config has:{RESET}")
        for p in providers:
            print(f"    {GREEN}✓{RESET} {p}")
        if existing.get("MODAL_TOKEN_ID"):
            print(f"    {GREEN}✓{RESET} Modal credentials")
    else:
        print(f"  {DIM}Existing .env appears empty.{RESET}")
    print()
    choice = prompt_choice(
        "What would you like to do?",
        [
            "Add or replace a provider (keeps everything else)",
            "Replace the entire config (start over)",
            "Cancel",
        ],
    )
    return {1: "add", 2: "replace", 3: "cancel"}[choice]


def cmd_init():
    banner()

    dest = CONFIG_DIR
    dest.mkdir(parents=True, exist_ok=True)
    print(f"  {DIM}Config directory: {dest}{RESET}")

    # Step 1 — check Docker
    step(1, 4, "Checking prerequisites")
    check_docker()

    # Step 2 — download compose file
    step(2, 4, "Downloading docker-compose.prod.yml")
    if (dest / COMPOSE_FILE).exists():
        warn(f"{COMPOSE_FILE} already exists, overwriting")
    download_file(COMPOSE_FILE, dest)

    # Step 3 — wizard. If config exists, give the user three paths so they
    # don't lose previously-entered keys when adding a new provider.
    step(3, 4, "Configuring secrets")

    existing = read_env(dest)
    config: dict[str, str]
    mode: str

    if existing:
        mode = _existing_config_choice(existing)
        if mode == "cancel":
            print(f"\n  Run {BOLD}trainable up{RESET} when you're ready.\n")
            return
        if mode == "add":
            # Carry forward everything; only re-prompt for what the user picks.
            config = dict(existing)
            print()
            print("  Pick what to add or replace; existing keys are preserved.")
            config.update(prompt_extra_providers(include_claude=True))
            # Modal — only re-prompt if missing.
            if not (config.get("MODAL_TOKEN_ID") and config.get("MODAL_TOKEN_SECRET")):
                print()
                print(
                    f"  {DIM}Modal tokens missing — need both for sandbox execution.{RESET}\n"
                )
                config["MODAL_TOKEN_ID"] = prompt_secret("Modal Token ID")
                config["MODAL_TOKEN_SECRET"] = prompt_secret("Modal Token Secret")
        else:  # replace
            config = {}
            config.update(prompt_claude_auth())
            config.update(prompt_extra_providers())
            print()
            print(
                f"  {DIM}Get your Modal tokens from https://modal.com/settings{RESET}\n"
            )
            config["MODAL_TOKEN_ID"] = prompt_secret("Modal Token ID")
            config["MODAL_TOKEN_SECRET"] = prompt_secret("Modal Token Secret")
    else:
        # Fresh install path
        config = {}
        config.update(prompt_claude_auth())
        config.update(prompt_extra_providers())
        print()
        print(f"  {DIM}Get your Modal tokens from https://modal.com/settings{RESET}\n")
        config["MODAL_TOKEN_ID"] = prompt_secret("Modal Token ID")
        config["MODAL_TOKEN_SECRET"] = prompt_secret("Modal Token Secret")

    print()
    write_env(dest, config)

    # Summary so the user can see what they ended up with.
    providers = configured_providers(config)
    if providers:
        print()
        print(f"  {BOLD}Configured providers:{RESET}")
        for p in providers:
            print(f"    {GREEN}✓{RESET} {p}")
    print(
        f"\n  {DIM}Tip: re-run {BOLD}trainable init{RESET}{DIM} (or "
        f"{BOLD}trainable reconfigure{RESET}{DIM}) anytime to add more keys.{RESET}"
    )

    # Step 4 — launch
    step(4, 4, "Ready to launch")
    print()
    answer = input(f"  Start trainable now? {DIM}[Y/n]{RESET}: ").strip().lower()
    if answer in ("", "y", "yes"):
        cmd_up()
    else:
        print(f"\n  Run {BOLD}trainable up{RESET} from anywhere when you're ready.\n")


def cmd_reconfigure():
    """Friendly alias for `trainable init` when config already exists."""
    if not (CONFIG_DIR / ENV_FILE).exists():
        warn(f"No existing config at {CONFIG_DIR}. Running fresh init.")
    cmd_init()


def _compose_args(subcommand: list[str]) -> list[str]:
    """Build `docker compose` args pinned to the global config directory."""
    compose = CONFIG_DIR / COMPOSE_FILE
    return [
        "docker",
        "compose",
        "--project-name",
        PROJECT_NAME,
        "--project-directory",
        str(CONFIG_DIR),
        "-f",
        str(compose),
        *subcommand,
    ]


def _require_config():
    compose = CONFIG_DIR / COMPOSE_FILE
    env = CONFIG_DIR / ENV_FILE
    if not compose.exists() or not env.exists():
        fail(
            f"Config not found at {CONFIG_DIR}. Run {BOLD}trainable init{RESET} first."
        )
        sys.exit(1)


def cmd_up():
    _require_config()

    print(f"\n{GREEN}{BOLD}Starting trainable...{RESET}")
    print(f"{DIM}  Frontend:      http://localhost:3000")
    print("  Backend API:   http://localhost:8000")
    print(f"  MinIO Console: http://localhost:9001{RESET}\n")

    os.execvp("docker", _compose_args(["up"]))


def cmd_down():
    _require_config()
    os.execvp("docker", _compose_args(["down"]))


USAGE = f"""\
{BOLD}trainable{RESET} — AI-powered ML experimentation platform

{BOLD}Usage:{RESET}
  trainable init           First-time setup wizard (writes config to ~/.trainable)
  trainable reconfigure    Add or replace LLM providers without losing existing keys
  trainable up             Start all services (works from any directory)
  trainable down           Stop all services

{BOLD}Quick start:{RESET}
  pip install trainable-ai
  trainable init
"""


def main():
    args = sys.argv[1:]
    cmd = args[0] if args else None

    if cmd == "init":
        cmd_init()
    elif cmd in ("reconfigure", "config"):
        cmd_reconfigure()
    elif cmd == "up":
        cmd_up()
    elif cmd == "down":
        cmd_down()
    else:
        print(USAGE)
        sys.exit(0 if cmd in ("-h", "--help") else 1)


if __name__ == "__main__":
    main()
