"""Trainable CLI — setup wizard and launcher."""

from __future__ import annotations

import getpass
import os
import shutil
import subprocess
import sys
import textwrap
import urllib.request
from pathlib import Path

REPO = "lucastononro/trainable"
BRANCH = "main"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"

COMPOSE_FILE = "docker-compose.prod.yml"
ENV_FILE = ".env"
PROJECT_NAME = "trainable"

# Config lives in ~/.trainable so `trainable up` works from any directory.
# Override via TRAINABLE_HOME env var for advanced users.
CONFIG_DIR = Path(os.environ.get("TRAINABLE_HOME", Path.home() / ".trainable"))

BOLD = "\033[1m"
DIM = "\033[2m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
CYAN = "\033[36m"
RED = "\033[31m"
RESET = "\033[0m"


def banner():
    print(
        textwrap.dedent(f"""\

        {BOLD}╔══════════════════════════════════════╗
        ║          trainable                   ║
        ║   AI-powered ML experimentation      ║
        ╚══════════════════════════════════════╝{RESET}
    """)
    )


def step(n: int, total: int, msg: str):
    print(f"\n{CYAN}{BOLD}[{n}/{total}]{RESET} {BOLD}{msg}{RESET}")


def success(msg: str):
    print(f"  {GREEN}✓{RESET} {msg}")


def warn(msg: str):
    print(f"  {YELLOW}!{RESET} {msg}")


def fail(msg: str):
    print(f"  {RED}✗{RESET} {msg}")


def prompt_secret(label: str, help_url: str | None = None) -> str:
    hint = f" {DIM}({help_url}){RESET}" if help_url else ""
    while True:
        value = getpass.getpass(f"  {label}{hint}: ").strip()
        if value:
            return value
        warn("Cannot be empty, try again.")


def prompt_choice(label: str, options: list[str]) -> int:
    print(f"  {label}")
    for i, opt in enumerate(options, 1):
        print(f"    {BOLD}{i}{RESET}) {opt}")
    while True:
        raw = input(f"  {DIM}Enter choice [1-{len(options)}]{RESET}: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return int(raw)
        warn(f"Please enter a number between 1 and {len(options)}")


def download_file(filename: str, dest: Path):
    url = f"{RAW_BASE}/{filename}"
    urllib.request.urlretrieve(url, dest / filename)
    success(f"Downloaded {filename}")


def check_docker():
    if not shutil.which("docker"):
        fail("Docker not found. Install it from https://docs.docker.com/get-docker/")
        sys.exit(1)
    result = subprocess.run(
        ["docker", "compose", "version"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail("Docker Compose not found. Install Docker Desktop or the compose plugin.")
        sys.exit(1)
    success("Docker and Docker Compose found")


def write_env(dest: Path, config: dict[str, str]):
    lines = ["# Generated by: trainable init", ""]

    if config.get("ANTHROPIC_API_KEY"):
        lines += [
            "# Claude authentication (API key)",
            f"ANTHROPIC_API_KEY={config['ANTHROPIC_API_KEY']}",
        ]
    elif config.get("CLAUDE_CODE_OAUTH_TOKEN"):
        lines += [
            "# Claude authentication (subscription token)",
            f"CLAUDE_CODE_OAUTH_TOKEN={config['CLAUDE_CODE_OAUTH_TOKEN']}",
        ]

    lines += [
        "",
        "# Modal (sandboxed code execution)",
        f"MODAL_TOKEN_ID={config['MODAL_TOKEN_ID']}",
        f"MODAL_TOKEN_SECRET={config['MODAL_TOKEN_SECRET']}",
    ]

    env_path = dest / ENV_FILE
    env_path.write_text("\n".join(lines) + "\n")
    success(f"Wrote {ENV_FILE}")


def prompt_claude_auth() -> dict[str, str]:
    print()
    choice = prompt_choice(
        "How would you like to authenticate with Claude?",
        [
            "Anthropic API key",
            "Claude subscription (Pro/Max) token",
        ],
    )
    print()

    if choice == 1:
        key = prompt_secret(
            "Anthropic API key",
            "https://console.anthropic.com",
        )
        return {"ANTHROPIC_API_KEY": key}

    # Subscription token flow
    print("  To get your subscription token, run this in another terminal:\n")
    print(f"    {BOLD}claude setup-token{RESET}\n")
    print("  Then paste the token below.\n")
    token = prompt_secret("Claude subscription token")
    return {"CLAUDE_CODE_OAUTH_TOKEN": token}


def cmd_init():
    banner()

    dest = CONFIG_DIR
    dest.mkdir(parents=True, exist_ok=True)
    print(f"  {DIM}Config directory: {dest}{RESET}")

    # Step 1 — check Docker
    step(1, 4, "Checking prerequisites")
    check_docker()

    # Step 2 — download compose file
    step(2, 4, "Downloading docker-compose.prod.yml")
    if (dest / COMPOSE_FILE).exists():
        warn(f"{COMPOSE_FILE} already exists, overwriting")
    download_file(COMPOSE_FILE, dest)

    # Step 3 — wizard
    step(3, 4, "Configuring secrets")

    config = {}

    # Claude auth
    config.update(prompt_claude_auth())

    # Modal auth
    print()
    print(f"  {DIM}Get your Modal tokens from https://modal.com/settings{RESET}\n")
    config["MODAL_TOKEN_ID"] = prompt_secret("Modal Token ID")
    config["MODAL_TOKEN_SECRET"] = prompt_secret("Modal Token Secret")

    print()
    if (dest / ENV_FILE).exists():
        warn(f"{ENV_FILE} already exists, overwriting")
    write_env(dest, config)

    # Step 4 — launch
    step(4, 4, "Ready to launch")
    print()
    answer = input(f"  Start trainable now? {DIM}[Y/n]{RESET}: ").strip().lower()
    if answer in ("", "y", "yes"):
        cmd_up()
    else:
        print(f"\n  Run {BOLD}trainable up{RESET} from anywhere when you're ready.\n")


def _compose_args(subcommand: list[str]) -> list[str]:
    """Build `docker compose` args pinned to the global config directory."""
    compose = CONFIG_DIR / COMPOSE_FILE
    return [
        "docker",
        "compose",
        "--project-name",
        PROJECT_NAME,
        "--project-directory",
        str(CONFIG_DIR),
        "-f",
        str(compose),
        *subcommand,
    ]


def _require_config():
    compose = CONFIG_DIR / COMPOSE_FILE
    env = CONFIG_DIR / ENV_FILE
    if not compose.exists() or not env.exists():
        fail(
            f"Config not found at {CONFIG_DIR}. Run {BOLD}trainable init{RESET} first."
        )
        sys.exit(1)


def cmd_up():
    _require_config()

    print(f"\n{GREEN}{BOLD}Starting trainable...{RESET}")
    print(f"{DIM}  Frontend:      http://localhost:3000")
    print("  Backend API:   http://localhost:8000")
    print(f"  MinIO Console: http://localhost:9001{RESET}\n")

    os.execvp("docker", _compose_args(["up"]))


def cmd_down():
    _require_config()
    os.execvp("docker", _compose_args(["down"]))


USAGE = f"""\
{BOLD}trainable{RESET} — AI-powered ML experimentation platform

{BOLD}Usage:{RESET}
  trainable init    One-time setup wizard (writes config to ~/.trainable)
  trainable up      Start all services (works from any directory)
  trainable down    Stop all services

{BOLD}Quick start:{RESET}
  pip install trainable-ai
  trainable init
"""


def main():
    args = sys.argv[1:]
    cmd = args[0] if args else None

    if cmd == "init":
        cmd_init()
    elif cmd == "up":
        cmd_up()
    elif cmd == "down":
        cmd_down()
    else:
        print(USAGE)
        sys.exit(0 if cmd in ("-h", "--help") else 1)


if __name__ == "__main__":
    main()
