"""initial schema

Revision ID: 0bae8e0f765d
Revises:
Create Date: 2026-07-18 23:25:19.238561

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0bae8e0f765d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("sandbox_config", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=True),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("dataset_ref", sa.String(length=512), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiments_project_id"), "experiments", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_experiments_session_id"), "experiments", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_experiments_state"), "experiments", ["state"], unique=False
    )
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("parent_hash", sa.String(length=64), nullable=True),
        sa.Column("source_session_id", sa.String(length=36), nullable=True),
        sa.Column("source_experiment_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_experiment_id"],
            ["experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_versions_hash"), "dataset_versions", ["hash"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_versions_kind"), "dataset_versions", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_versions_parent_id"),
        "dataset_versions",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_versions_project_id"),
        "dataset_versions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_versions_source_experiment_id"),
        "dataset_versions",
        ["source_experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_versions_source_session_id"),
        "dataset_versions",
        ["source_session_id"],
        unique=False,
    )
    op.create_table(
        "registered_models",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_session_id", sa.String(length=36), nullable=True),
        sa.Column("artifact_uri", sa.String(length=512), nullable=False),
        sa.Column("artifact_size_bytes", sa.Integer(), nullable=True),
        sa.Column("metrics_summary", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hyperparams", sa.JSON(), nullable=True),
        sa.Column("dataset_refs", sa.JSON(), nullable=True),
        sa.Column("metrics_history", sa.JSON(), nullable=True),
        sa.Column("serving_app_path", sa.String(length=512), nullable=True),
        sa.Column("api_key", sa.String(length=64), nullable=True),
        sa.Column("framework", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registered_models_experiment_id"),
        "registered_models",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registered_models_project_id"),
        "registered_models",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registered_models_source_session_id"),
        "registered_models",
        ["source_session_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("experiment_id", sa.String(length=36), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_experiment_id"), "sessions", ["experiment_id"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_project_id"), "sessions", ["project_id"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("s3_path", sa.String(length=512), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_session_id"), "artifacts", ["session_id"], unique=False
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_url", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("modal_app", sa.String(length=255), nullable=True),
        sa.Column("modal_function", sa.String(length=255), nullable=True),
        sa.Column("compute", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["registered_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_model_id"), "deployments", ["model_id"], unique=False
    )
    op.create_table(
        "experiment_datasets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_version_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"], ["dataset_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_datasets_dataset_version_id"),
        "experiment_datasets",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_datasets_experiment_id"),
        "experiment_datasets",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "log_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("run_tag", sa.String(length=100), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_events_session_id"), "log_events", ["session_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_session_id"), "messages", ["session_id"], unique=False
    )
    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("run_tag", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metrics_session_id"), "metrics", ["session_id"], unique=False
    )
    op.create_table(
        "processed_dataset_meta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("feature_columns", sa.JSON(), nullable=True),
        sa.Column("target_column", sa.String(length=255), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("train_rows", sa.Integer(), nullable=True),
        sa.Column("val_rows", sa.Integer(), nullable=True),
        sa.Column("test_rows", sa.Integer(), nullable=True),
        sa.Column("quality_stats", sa.JSON(), nullable=True),
        sa.Column("source_files", sa.JSON(), nullable=True),
        sa.Column("output_files", sa.JSON(), nullable=True),
        sa.Column("s3_synced", sa.String(length=10), nullable=True),
        sa.Column("s3_prefix", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_dataset_meta_experiment_id"),
        "processed_dataset_meta",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_dataset_meta_session_id"),
        "processed_dataset_meta",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "run_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("dataset_hash", sa.String(length=64), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=True),
        sa.Column("hyperparams", sa.JSON(), nullable=True),
        sa.Column("env_lockfile", sa.Text(), nullable=True),
        sa.Column("manifest_uri", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_snapshots_experiment_id"),
        "run_snapshots",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_snapshots_session_id"),
        "run_snapshots",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("active_form", sa.String(length=255), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_session_id"), "tasks", ["session_id"], unique=False)
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("agent_type", sa.String(length=50), nullable=True),
        sa.Column("agent_id", sa.String(length=100), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_input_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_creation_input_tokens", sa.Integer(), nullable=True),
        sa.Column("sandbox_seconds", sa.Float(), nullable=True),
        sa.Column("gpu_type", sa.String(length=50), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_events_project_id"), "usage_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_events_session_id"), "usage_events", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_events_session_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_project_id"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(op.f("ix_tasks_session_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_run_snapshots_session_id"), table_name="run_snapshots")
    op.drop_index(op.f("ix_run_snapshots_experiment_id"), table_name="run_snapshots")
    op.drop_table("run_snapshots")
    op.drop_index(
        op.f("ix_processed_dataset_meta_session_id"),
        table_name="processed_dataset_meta",
    )
    op.drop_index(
        op.f("ix_processed_dataset_meta_experiment_id"),
        table_name="processed_dataset_meta",
    )
    op.drop_table("processed_dataset_meta")
    op.drop_index(op.f("ix_metrics_session_id"), table_name="metrics")
    op.drop_table("metrics")
    op.drop_index(op.f("ix_messages_session_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_log_events_session_id"), table_name="log_events")
    op.drop_table("log_events")
    op.drop_index(
        op.f("ix_experiment_datasets_experiment_id"), table_name="experiment_datasets"
    )
    op.drop_index(
        op.f("ix_experiment_datasets_dataset_version_id"),
        table_name="experiment_datasets",
    )
    op.drop_table("experiment_datasets")
    op.drop_index(op.f("ix_deployments_model_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_artifacts_session_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_sessions_project_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_experiment_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_registered_models_source_session_id"), table_name="registered_models"
    )
    op.drop_index(
        op.f("ix_registered_models_project_id"), table_name="registered_models"
    )
    op.drop_index(
        op.f("ix_registered_models_experiment_id"), table_name="registered_models"
    )
    op.drop_table("registered_models")
    op.drop_index(
        op.f("ix_dataset_versions_source_session_id"), table_name="dataset_versions"
    )
    op.drop_index(
        op.f("ix_dataset_versions_source_experiment_id"), table_name="dataset_versions"
    )
    op.drop_index(op.f("ix_dataset_versions_project_id"), table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_parent_id"), table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_kind"), table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_hash"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(op.f("ix_experiments_state"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_session_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_project_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_table("projects")
    # ### end Alembic commands ###
