"""Serving launcher — boots a model's generated handler from the volume.

The serving endpoint's template points every deployed model at this same
image; the model-specific handler.py (generated by create-serving-app,
written to the network volume) is selected via the HANDLER_PATH env var
on the endpoint. Executing it starts `runpod.serverless.start(...)` with
the model's predict handler.
"""

import os
import runpy
import sys

handler_path = os.environ.get("HANDLER_PATH")
if not handler_path:
    print("[serving] HANDLER_PATH env var is not set", file=sys.stderr)
    sys.exit(1)
if not os.path.exists(handler_path):
    print(f"[serving] handler not found at {handler_path}", file=sys.stderr)
    sys.exit(1)

runpy.run_path(handler_path, run_name="__main__")
